apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-blue
images:
- name: hello-gitops
  newName: pavlozabavskyi/hello-gitops
  newTag: c4012f0ca97eb9cc5868aac68f8fb9cb370c51d5
