apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: pavlozabavskyi/hello-gitops
  newTag: 178b149521b10b8c46c85e35f8a728406367c0d6
