apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-blue
images:
- name: hello-gitops
  newName: pavlozabavskyi/hello-gitops
  newTag: 9e61cb38ef1dc0b9e96b8bbcced5fc16aa53b92b
