apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
data:
  gf-security-admin-user: YWRtaW4= # this is taken by running echo -n admin | base64
  gf-security-admin-password: Z3JhZmFuYQ== # this is taken by running echo -n grafana | base64